apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql2019-sample
#--test is the OpenShift project name used for the deployment.
  namespace: test
#--Add an OpenShift Application (part-of) not a single POD.
  labels:
    app: mssql2019-sample
    app.kubernetes.io/name: mssql
    app.kubernetes.io/part-of: my-app
#--
spec:
  selector:
    matchLabels:
      app: mssql2019-sample
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql2019-sample
    spec:
      containers:
        - name: mssql2019-c
          image: "mcr.microsoft.com/mssql/server:2019-latest"
          ports:
            - containerPort: 1433
#Attention: POD can stay in pending state if not enought resources are available.
          resources:
            limits:
              memory: 3Gi
              cpu: "2"
            requests:
              memory: 2Gi
              cpu: "1"
          env:
          - name: MSSQL_PID
            value: "Developer"
          - name: SA_PASSWORD
            value: "SQLserver2019"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_MEMORY_LIMIT_MB
            value: "2Gi"
#Attention: command tag can be limited depending on the image (like CMD tag in a Dockerfile).
          command: ["bin/sh"]
          args: ["ls"]
