apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql2019-sample
  namespace: ocp-demo
#--Ajouter une App OpenShift (part-of) + iconDonet (name) et pas seulement un Deployment
  labels:
    app: mssql2019-sample
    app.kubernetes.io/name: mssql
    app.kubernetes.io/part-of: myaspnet1
#--
spec:
  selector:
    matchLabels:
      app: mssql2019-sample
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql2019-sample
    spec:
      containers:
        - name: mssql2019-c
          image: "mcr.microsoft.com/mssql/server:2019-latest"
          ports:
            - containerPort: 1433
          resources:
            limits:
              memory: 3Gi
              cpu: "2"
            requests:
              memory: 2Gi
              cpu: "1"
          env:
          - name: MSSQL_PID
            value: "Developer"
          - name: SA_PASSWORD
            value: "SQLserver2019"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_MEMORY_LIMIT_MB
            value: "2Gi"
#Attention: command pas toujours accepte par image (idem que CMD dans Dockerfile)
          command: ["bin/sh"]
          args: ["ls"]
